# Generated by Django 5.2.3 on 2025-07-01 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booksmanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('borrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
